# Generated by Django 4.2.7 on 2023-12-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedetails',
            old_name='Mname',
            new_name='Moname',
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='seat_available',
            field=models.IntegerField(),
        ),
    ]
